// Artist detail for Hinterland 2026. Keys must match the names in data.js exactly.
// Researched July 25, 2026 from press, label pages, and the festival site.
// `uncertain: true` marks acts where solid sourcing was thin — mostly small
// local bookings. The app shows a caveat on those.

Object.assign(ARTISTS, {

  // ── Thursday ────────────────────────────────────────────────────

  'Porch Light': {
    genre: 'Indie rock',
    origin: 'Minneapolis, Minnesota',
    blurb: 'A five-piece that formed in summer 2024 and blew up fast off house-show clips, selling out rooms before they had much recorded output. Jackie Uhas sings close-miked and conversational over shimmering twin guitars, and songs that start bedroom-quiet open into full-band crescendos. Good early-afternoon pick if you want melodic guitar music rather than a beat drop.',
    soundsLike: ['Slow Pulp', 'Paramore', 'Big Thief'],
    keyTracks: ['Fall Back', 'Honey'],
  },
  'Frost Children': {
    genre: 'Hyperpop / electronic',
    origin: 'St. Louis → New York City',
    blurb: 'Sibling duo Angel and Lulu Prost, now fixtures of the New York underground. They mash EDM, Jersey club, bloghouse, punk and bubblegum electronics into short, overclocked songs, and the live show is closer to a sweaty rave than a band set. Their 2025 album SISTER pulled in more ’90s rock and indie-sleaze texture.',
    soundsLike: ['100 gecs', 'Charli xcx', 'Sophie'],
    keyTracks: ['FLATLINE', 'Falling', 'Control'],
  },
  'Jane Remover': {
    genre: 'Hyperpop / shoegaze',
    origin: 'New Jersey → Chicago',
    blurb: 'One of the most restless musicians in online music: helped pioneer the dariacore microgenre as a teenager, swerved into cavernous shoegaze on 2023’s Census Designated, then back into abrasive rap-forward electronics on 2025’s Revengeseekerz. Expect blown-out distortion, sudden tempo whiplash, and vocals buried in the mix by design. Not background music.',
    soundsLike: ['Bladee', 'My Bloody Valentine', 'underscores'],
    keyTracks: ['JRJRJR', 'Dancing with Your Eyes Closed', 'Dreamflasher'],
  },
  'Oklou': {
    genre: 'Ambient pop',
    origin: 'Poitiers, France',
    blurb: 'Marylou Mayniel is classically trained on piano and cello and makes what she calls drumless pop — soft, high, breathy vocals over flickering synths with very little percussion underneath. Her 2025 debut Choke Enough, co-produced with A.G. Cook and Danny L Harle, mixes Y2K nostalgia with almost baroque harmony. A calm, hypnotic set, not a high-energy one.',
    soundsLike: ['Caroline Polachek', 'Grimes', 'Bladee'],
    keyTracks: ['blade bird', 'harvest sky', 'family and friends'],
  },
  'AUDREY NUNA': {
    genre: 'Alt-R&B / hip-hop',
    origin: 'Manalapan, New Jersey',
    blurb: 'Korean-American singer-rapper Audrey Chu slides between laid-back sung hooks and deadpan rap verses over woozy, trap-leaning production. She built a following off 2021’s a liquid breakfast, then reached a much bigger audience as one of the singing voices on KPop Demon Hunters and its chart-topping “Golden.” Cool-toned and understated live — more groove than spectacle.',
    soundsLike: ['Doja Cat', 'Kali Uchis', 'Rico Nasty'],
    keyTracks: ['damn Right', 'Comic Sans', 'Golden'],
  },
  'ASHNIKKO': {
    genre: 'Hyperpop / nu-metal',
    origin: 'North Carolina → London',
    blurb: 'Known for blue hair, an anime-and-video-game visual world, and songs that swing between bratty rap verses and industrial nu-metal breakdowns. DEMIDEVIL made her a viral name with blunt sex-and-revenge lyrics; 2023’s WEEDKILLER went heavier and more allegorical with eco-apocalypse worldbuilding. High-theatrics, high-volume, lots of crowd chanting.',
    soundsLike: ['Rico Nasty', 'Poppy', 'Charli xcx'],
    keyTracks: ['Daisy', 'STUPID', 'Slumber Party'],
  },
  'beabadoobee': {
    genre: 'Indie rock / bedroom pop',
    origin: 'Iloilo, Philippines → London',
    blurb: 'Beatrice Laus went from lo-fi bedroom demos (“Coffee,” later sampled on “Death Bed”) to full ’90s-alt-rock records. Her 2024 album This Is How Tomorrow Moves was made with Rick Rubin and is warmer and more acoustic-leaning, with strings and clean guitar tones alongside the fuzzier back catalogue. Melodic, unfussy guitar-pop — a good singalong before the headliner.',
    soundsLike: ['Clairo', 'Alvvays', 'Soccer Mommy'],
    keyTracks: ['Coffee', 'Glue Song', 'Take a Bite'],
  },
  'KATSEYE': {
    genre: 'Global pop / K-pop',
    origin: 'Los Angeles, California',
    blurb: 'Six-member girl group assembled in LA through HYBE and Geffen’s Dream Academy competition, with members from the Philippines, South Korea, Switzerland and the US. They apply K-pop training and choreography to English-language Western pop, and broke through with “Touch” and the deliberately obnoxious “Gnarly.” Fully staged set with tight synchronized dance — the biggest production of the day.',
    soundsLike: ['Fifth Harmony', 'TWICE', 'Charli xcx'],
    keyTracks: ['Touch', 'Gnarly', 'Debut'],
  },
  'Duo Beats': {
    genre: 'Jazz punk / instrumental',
    origin: 'Des Moines, Iowa',
    blurb: 'A local band whose running joke is the name: a quintet called Duo that self-describes as sounding like five people playing instruments at the same time. Their record Training In Stilll Life is tagged jazz punk — guitar, bass, drums plus synths, samples and guest trumpet. Very much a local-scene curiosity rather than a touring name, so expect something scrappy and off-kilter.',
    soundsLike: ['Battles', 'Hella', 'BADBADNOTGOOD'],
    keyTracks: ['Clover', 'Homer', 'Spy Vs Spy'],
    uncertain: true,
  },
  'Lipstick Homicide': {
    genre: 'Pop punk / riot grrrl',
    origin: 'Iowa City, Iowa',
    blurb: 'Iowa City DIY veterans who started as high schoolers around 2006 and have toured the US, Canada and Europe since. Rachel Feldmann and Kane Edwards trade vocals over fast power chords and big melodic hooks, with a riot-grrrl streak and a self-applied “gay Green Day” tag. Short, loud, sub-three-minute songs — the hometown set on this bill.',
    soundsLike: ['Green Day', 'Bikini Kill', 'The Muffs'],
    keyTracks: ['Rockerchick', 'So Happy For You', 'This Time For Real'],
  },
  'Nourished by Time': {
    genre: 'Alt-R&B / synth-pop',
    origin: 'Baltimore, Maryland',
    blurb: 'Marcus Brown recorded his Best New Music debut Erotic Probiotic 2 in his parents’ basement. He sings in a low croony baritone over cheap-sounding drum machines and ’80s synths, with lyrics about heartbreak, work and anti-capitalism that land more bitter than nostalgic. His 2025 album The Passionate Ones was named Paste’s album of the year, so this late slot is a real draw.',
    soundsLike: ['Blood Orange', 'Prince', 'Arthur Russell'],
    keyTracks: ['Daddy', 'The Fields', '9 2 5'],
  },
  'Pixel Grip': {
    genre: 'Darkwave / EBM',
    origin: 'Chicago, Illinois',
    blurb: 'Chicago trio built around vocalist Rita Lukea, playing dominatrix-energy body music: pounding EBM kicks, cold minimal synths, and spoken-sung commands over the top. Their 2021 album Arena is the calling card; 2025’s Percepticide is darker and more industrial. This is the 12:30 AM slot for a reason — it’s a club set, not a rock set.',
    soundsLike: ['Boy Harsher', 'Nine Inch Nails', 'Chromatics'],
    keyTracks: ['ALPHAPUSSY', 'Demon Chaser', 'Pursuit'],
  },

  // ── Friday ──────────────────────────────────────────────────────

  'Saint Avangeline': {
    genre: 'Ethereal goth / dream pop',
    origin: 'Atlanta, Georgia',
    blurb: 'Adeline Troutman makes dark, cathedral-sized dream pop that keeps drifting toward metal — clean ethereal vocals stacked over guitars that occasionally get genuinely heavy. Her breakout “Lilith” went viral and has racked up tens of millions of streams, using biblical imagery to write about toxic relationships. Gothic-literary mood music with real teeth.',
    soundsLike: ['Chelsea Wolfe', 'Ethel Cain', 'Lana Del Rey'],
    keyTracks: ['Lilith', 'Gardener of Eden', 'Your Rarest of Flowers'],
  },
  'Wisp': {
    genre: 'Shoegaze',
    origin: 'San Francisco Bay Area',
    blurb: 'Natalie Lu was a teenager when her first-ever single “Your Face” blew up in 2023 and landed on Billboard’s Hard Rock chart. She plays the classic formula straight — walls of blown-out guitar, buried breathy vocals, My Bloody Valentine worship — and does it well enough that Interscope signed her almost immediately. Expect volume and haze rather than banter.',
    soundsLike: ['My Bloody Valentine', 'Slowdive', 'Whirr'],
    keyTracks: ['Your Face', 'Once Again', 'Sword'],
  },
  'SOFIA ISELLA': {
    genre: 'Dark art pop',
    origin: 'Los Angeles, California',
    blurb: 'A 21-year-old singer-producer and trained violinist whose songs are half pop hook, half spoken-word monologue delivered in an unsettling deadpan. Lyrically she goes straight at misogyny, religion and the performance of womanhood. The live show leans theatrical and creepy — go if you want something with a point of view, skip if you want background music.',
    soundsLike: ['Fiona Apple', 'Poppy', 'Marina'],
    keyTracks: ['Hot Gum', 'Us and Pigs', 'All of Human Knowledge Made Us Dumb'],
  },
  'Paris Paloma': {
    genre: 'Dark indie folk',
    origin: 'Derbyshire, England',
    blurb: 'Her 2023 single “Labour” — a bitter, chant-along indictment of unequal domestic work — became a genuine TikTok-to-radio crossover. Her writing pulls from mythology, folklore and art history over acoustic guitar and layered group vocals, and 2024’s Cacophony expands that into something fuller and angrier. This is a singalong set: the crowd will know every word of the chorus.',
    soundsLike: ['Hozier', 'Florence + The Machine', 'Ethel Cain'],
    keyTracks: ['Labour', 'the fruits', 'notre dame'],
  },
  'Snow Strippers': {
    genre: 'Witch house / electroclash',
    origin: 'Detroit, Michigan',
    blurb: 'Duo Tatiana Schwaninger and Graham Perez make blown-out, distorted club music — trance stabs, hardstyle kicks and witch-house murk under hooky detached vocals. “Under Your Spell” broke them online and Lil Uzi Vert jumped on a remix of “It’s A Dream.” Loud, fast and cheerfully trashy; closest reference point is Crystal Castles at a warehouse party.',
    soundsLike: ['Crystal Castles', 'SALEM', 'Sleigh Bells'],
    keyTracks: ['Under Your Spell', 'It’s A Dream', 'Know My Name'],
  },
  'MUNA': {
    genre: 'Queer synth-pop',
    origin: 'Los Angeles, California',
    blurb: 'Katie Gavin, Josette Maskin and Naomi McPherson write enormous, emotionally precise synth-pop about heartbreak and queer joy — and they are one of the best live bands in that lane, with real guitar solos and a crowd that treats the shows like church. “Silk Chiffon” is the calling card but “I Know a Place” still lands hardest. Highest-energy singalong of the evening.',
    soundsLike: ['Robyn', 'Carly Rae Jepsen', 'HAIM'],
    keyTracks: ['Silk Chiffon', 'I Know a Place', 'Anything But Me'],
  },
  'Lorde': {
    genre: 'Alternative pop',
    origin: 'Auckland, New Zealand',
    blurb: 'Friday’s headliner, four albums deep and touring 2025’s Virgin — a return to sparse, hard-edged electronic production after the acoustic detour of Solar Power. Sets pull across the whole catalogue, so expect Pure Heroine and Melodrama staples alongside “What Was That” and “Hammer,” plus the physical, unpolished stage presence she’s built this era around.',
    soundsLike: ['Charli xcx', 'FKA twigs', 'Caroline Polachek'],
    keyTracks: ['Royals', 'Green Light', 'What Was That'],
  },
  'Crooked Torus': {
    genre: 'Experimental psych rock',
    origin: 'Des Moines, Iowa',
    blurb: 'A two-piece — Javs, originally from Peru, and Jor from Iowa — playing instrumental-leaning psychedelic rock with prog structures and a lot of pedal-board texture. They describe themselves as one part Peruvian prog rock, one part Southside wizardry, and the records back that up: long, drifting, riff-driven jams rather than songs. Worth catching if you like your psych instrumental and loose.',
    soundsLike: ['Earthless', 'King Gizzard & The Lizard Wizard', 'Boris'],
    keyTracks: ['Torus Slide', 'Mystic Fire', 'Acidlord'],
  },
  'Sarah Tonin': {
    genre: 'Queer avant-pop',
    origin: 'Des Moines, Iowa',
    blurb: 'A self-described queer avant-pop band that grew out of a solo singer-songwriter project via the Girls Rock! program. They’re a fixture of the Iowa DIY circuit around venues like xBk, with a reputation for unpredictable, hook-heavy sets that swerve between emo, indie and outright art-pop.',
    soundsLike: ['Illuminati Hotties', 'Vundabar', 'Palehound'],
    keyTracks: ['red lights // love letters', 'flowers', 'an excuse to give up'],
    uncertain: true,
  },
  "Leslie & The Ly's": {
    genre: 'Comedy electro-rap',
    origin: 'Ames, Iowa',
    blurb: 'Iowa’s own absurdist institution: Leslie Hall built a career on gold spandex, a collection of 400-plus rhinestone “gem sweaters,” and deadpan electro-rap about tight pants and body rolls. The live show is pure spectacle — costume changes, choreography, a touring gem sweater museum in the van. This is a hometown comedy set, not a music-first one, and the crowd will be in on the joke.',
    soundsLike: ['Peaches', 'The Lonely Island', 'Le Tigre'],
    keyTracks: ['Gem Sweater', 'Tight Pants / Body Rolls', 'Zombie Killer'],
  },
  'Between Friends': {
    genre: 'Bedroom pop',
    origin: 'Los Angeles, California',
    blurb: 'Sibling duo Brandon and Savannah Hudson making what they call laptop dream pop — soft, blurry vocals over warm electronic production, built for late nights rather than daylight. “affection” has passed 200 million streams and their 2023 album filled out the sound. With an 11:30 PM slot, this is the mellow after-hours option.',
    soundsLike: ['Clairo', 'beabadoobee', 'Still Woozy'],
    keyTracks: ['affection', 'Eyes on my baby', 'Pleasure delayer'],
  },
  'Ninajirachi': {
    genre: 'Hyperpop / club EDM',
    origin: 'New South Wales, Australia',
    blurb: 'Producer-DJ Nina Wilson makes what she calls girl EDM — high-BPM, glitchy, Y2K-nostalgic club music that sits between hyperpop and proper festival dance. Her 2025 debut album I Love My Computer got broad critical praise and made her one of the biggest new electronic acts in Australia. She closes Friday at 12:30 AM, and it’s a full DJ set: come to dance, not to watch.',
    soundsLike: ['A. G. Cook', 'Sophie', 'Nina Las Vegas'],
    keyTracks: ['iPod Touch', 'Fuck My Computer', 'Middle of the Night'],
  },

  // ── Saturday ────────────────────────────────────────────────────

  'Amble': {
    genre: 'Irish acoustic folk',
    origin: 'Leitrim / Longford / Sligo, Ireland',
    blurb: 'A three-part acoustic outfit built on guitar, mandolin and tight vocal harmony rather than big production. They formed in 2022 after three strangers landed on the same bill, quit their teaching and data-science jobs, and topped the Irish album chart in 2025 with the mostly-live-recorded Reverie. Quiet, story-driven songs about home and memory that a big crowd tends to sing back at them.',
    soundsLike: ['The Lumineers', 'Villagers', 'Passenger'],
    keyTracks: ['Mariner Boy', 'Lonely Island', 'Schoolyard Days'],
  },
  'Waylon Wyatt': {
    genre: 'Red dirt country',
    origin: 'Hackett, Arkansas',
    blurb: 'A 19-year-old who blew up off TikTok with “Everything Under the Sun,” a heartbreak song written on a trailer porch during a construction job. His sound is stripped-back and lyric-first — Americana and red dirt country in the Tyler Childers lineage, not the polished Nashville kind. He’s opened for Childers and Turnpike Troubadours and released his debut Dustpiles in 2026.',
    soundsLike: ['Tyler Childers', 'Zach Bryan', 'Turnpike Troubadours'],
    keyTracks: ['Everything Under the Sun', 'Arkansas Diamond', 'Phoning Heaven'],
  },
  'Julia Wolf': {
    genre: 'Alt-pop',
    origin: 'Long Island, New York',
    blurb: 'A singer-producer who makes self-produced alt-pop with a deadpan, whispery delivery over beats that swing from low-slung 808s to distorted guitars. Her 2021 EP Girls in Purgatory built the cult following; 2025’s PRESSURE pushed her further into dissonant, heavy indie-rock territory. Good pick if you want something moody and modern rather than another guitar band.',
    soundsLike: ['Caroline Polachek', 'Billie Eilish', 'Blackbear'],
    keyTracks: ['Falling in Love', 'Gothic Babe Tendencies', 'Get Off My'],
  },
  'CMAT': {
    genre: 'Country-pop',
    origin: 'Dublin, Ireland',
    blurb: 'Ciara Mary-Alice Thompson plays country the way a theater kid would — huge hooks, jokes that turn devastating two lines later, and a genuinely enormous voice. Three straight Irish number-one albums, capped by 2025’s Euro-Country, a record about the wreckage of the Celtic Tiger crash. One of the most physically committed sets on any festival bill; she does not stand still.',
    soundsLike: ['Kacey Musgraves', 'Self Esteem', 'Dolly Parton'],
    keyTracks: ['Take a Sexy Picture of Me', 'Stay for Something', 'EURO-COUNTRY'],
  },
  'Santigold': {
    genre: 'Genre-blending alt-pop',
    origin: 'Philadelphia → Brooklyn',
    blurb: 'Santi White broke out in 2008 with a self-titled debut that shuffled dub, new wave, post-punk and hip-hop into something nobody had a name for, and she’s been ahead of the curve since. Her set is beat-heavy and hook-heavy with a strong visual and choreography element — closer to a party than a singer-songwriter showcase.',
    soundsLike: ['M.I.A.', 'TV on the Radio', 'Yeah Yeah Yeahs'],
    keyTracks: ['L.E.S. Artistes', 'Disparate Youth', 'Creator'],
  },
  'The Format': {
    genre: 'Indie power-pop',
    origin: 'Peoria, Arizona',
    blurb: 'Nate Ruess and Sam Means’ duo made two beloved records in the mid-2000s, broke up in 2008, and Ruess went on to front fun. They reunited for real in late 2025 and released Boycott Heaven in 2026, their first album in 20 years. Big, brass-and-harmony-stacked pop with ’60s–’70s bones — a lot of this crowd waited two decades to hear “The First Single” live.',
    soundsLike: ['fun.', 'Jimmy Eat World', 'Ben Folds'],
    keyTracks: ['The First Single', 'She Doesn’t Get It', 'Dog Problems'],
  },
  'Jessie Murph': {
    genre: 'Country-trap pop',
    origin: 'Huntsville, Alabama',
    blurb: 'Came up posting covers on TikTok and now makes a genuinely strange hybrid: hip-hop production and trap drums under a raw, cracked country voice. She’s charted with Jelly Roll and Maren Morris, and her 2025 album Sex Hysteria leaned hard into provocation. Expect a young, loud crowd and songs that go from whispered to screamed.',
    soundsLike: ['Jelly Roll', 'Ashnikko', 'Lana Del Rey'],
    keyTracks: ['Wild Ones (with Jelly Roll)', 'Always Been You', 'How Could You'],
  },
  'Mumford & Sons': {
    genre: 'Folk rock',
    origin: 'London, England',
    blurb: 'The band that put banjos and stomping four-part choruses on arena stages with Sigh No More and Babel. After a detour into electric rock in the late 2010s, 2025’s Rushmere returned them to the acoustic build-and-explode formula. As a headliner they’re a reliable mass singalong — “I Will Wait” and “The Cave” with 20,000 people is the whole reason to be down front.',
    soundsLike: ['The Lumineers', 'Of Monsters and Men', 'Kings of Leon'],
    keyTracks: ['Little Lion Man', 'I Will Wait', 'The Cave'],
  },
  'Derry & the Dirty Dishes': {
    genre: 'Kids’ rock',
    origin: 'Des Moines, Iowa',
    blurb: 'A band making rock for kids and the adults hauling them around, fronted by Derek Muse Lambert. Their debut Three Day Weekend runs from raucous kid-friendly punk to playful indie rock to quirky folk-country, with songs about garbage trucks, cats, and a baby stealing a minivan. They play the Miniland family stage — go if you have small humans with you, or want something silly and low-stakes.',
    soundsLike: ['They Might Be Giants', 'The Aquabats', 'Caspar Babypants'],
    keyTracks: ['Garbage Truck', 'New Attitude'],
    uncertain: true,
  },
  'Quintron & Miss Pussycat': {
    genre: 'Swamp-tech garage',
    origin: 'New Orleans, Louisiana',
    blurb: 'A Ninth Ward duo running 25-plus years and 17-plus albums of what Quintron calls swamp-tech — Hammond organ, homemade distorted instruments, and his patented light-activated Drum Buddy synth pushing loud, danceable, half-broken party music. Miss Pussycat opens and closes the set with elaborate hand-built puppet shows under black light. The weirdest thing on the Saturday bill by a mile.',
    soundsLike: ['The Cramps', 'Of Montreal', 'Black Lips'],
    keyTracks: ['Swamp Buggy Badass', 'Ring the Alarm', 'Waterfall'],
    uncertain: true,
  },
  'The Brook & The Bluff': {
    genre: 'Indie folk-soul',
    origin: 'Birmingham, Alabama → Nashville',
    blurb: 'Started as an acoustic duo named for the Mountain Brook and Bluff Park neighborhoods, now a four-piece built on silken harmonies, tight grooves and clean melodic guitar work. Records like Yard Sale and Bluebeard lean ’70s-warm; 2026’s Wearwolf is louder and closer to their live energy. Easy, groove-forward listening that works well in an afternoon field.',
    soundsLike: ['Fleet Foxes', 'The Head and the Heart', 'Dawes'],
    keyTracks: ['Halfway Up', 'Everything Is Just a Mess', 'Masks'],
  },
  'Buffalo Traffic Jam': {
    genre: 'Indie folk duo',
    origin: 'Bozeman, Montana',
    blurb: 'Frankie Cassidy and Nathan Ross met at Montana State and started releasing music in 2024; the gritty “Forgot Your Roots” went viral and “Fool’s Gold” got even bigger in late 2025. Their EP Take Me Home has cleared 8 million streams. Heartfelt acoustic songwriting with a lot of open space in it — well suited to the Campfire Stage.',
    soundsLike: ['Dylan Gossett', 'Noah Kahan', 'The Head and the Heart'],
    keyTracks: ['Forgot Your Roots', 'Fool’s Gold', 'Rescue Me'],
  },

  // ── Sunday ──────────────────────────────────────────────────────

  'Haute & Freddy': {
    genre: 'Theatrical synth-pop',
    origin: 'Los Angeles, California',
    blurb: 'A duo of career pop songwriters — Michelle Buzz wrote for Katy Perry and Kylie Minogue, Lance Shipp produced for Britney Spears — who reinvented themselves as 18th-century runaway carnival characters. Expect ruffled shirts, tricorne hats, wigs, and big ’80s new-wave synth hooks played completely straight. Their debut Big Disgrace landed in March 2026.',
    soundsLike: ['Chappell Roan', 'Eurythmics', 'Kate Bush'],
    keyTracks: ['Scantily Clad', 'Dance the Pain Away', 'Shy Girl'],
  },
  'Samia': {
    genre: 'Indie folk-rock',
    origin: 'Los Angeles → Minneapolis',
    blurb: 'Samia Najimy Finnerty writes plainspoken, uncomfortably specific songs about jealousy, friendship and self-destruction, then buries them in hooks so you sing along before you notice what you’re saying. Her 2025 album Bloodless traded the pop sheen of Honey for a darker Americana-gothic sound. Good if you want lyrics you’ll think about later; less good if you want to dance.',
    soundsLike: ['Lucy Dacus', 'Mitski', 'Fiona Apple'],
    keyTracks: ['Kill Her Freak Out', 'Charm You', 'Honey'],
  },
  'Audrey Hobert': {
    genre: 'Conversational pop',
    origin: 'Los Angeles, California',
    blurb: 'An NYU screenwriting grad and former Nickelodeon staff writer who co-wrote much of Gracie Abrams’ The Secret of Us with her roommate before going solo. Her 2025 debut Who’s the Clown? plays like voice memos from your funniest friend — talky, over-detailed, frequently mortifying, with real melodies underneath.',
    soundsLike: ['Gracie Abrams', 'Lily Allen', 'Olivia Rodrigo'],
    keyTracks: ['Sue Me', 'Chateau', 'Thirst Trap'],
  },
  'Suki Waterhouse': {
    genre: 'Dream pop',
    origin: 'London, England',
    blurb: 'The model-actor turned Sub Pop signee has built a genuinely good hazy retro-pop catalog — reverb-drenched guitars, vintage keys, low intimate vocals, songs about wanting someone who isn’t paying attention. “Good Looking” blew up in 2022 and pulled a real audience into records like Memoir of a Sparklemuffin. A mood set: soft-focus and cinematic rather than high-energy.',
    soundsLike: ['Lana Del Rey', 'Mazzy Star', 'Beach House'],
    keyTracks: ['Good Looking', 'Moves', 'My Fun'],
  },
  'Wet Leg': {
    genre: 'Post-punk / indie rock',
    origin: 'Isle of Wight, England',
    blurb: 'The band that turned deadpan 2021 novelty hit “Chaise Longue” into a Grammy-winning career, now a full five-piece with a heavier, hornier second album in 2025’s Moisturizer. Rhian Teasdale delivers absurd one-liners over scrappy, loud guitars, and live they’re much more aggressive than the records suggest. One of the safest bets on Sunday for a crowd that actually moves.',
    soundsLike: ['Yeah Yeah Yeahs', 'Dry Cleaning', 'Amyl and the Sniffers'],
    keyTracks: ['Chaise Longue', 'Wet Dream', 'Catch These Fists'],
  },
  'Geese': {
    genre: 'Art rock / experimental',
    origin: 'Brooklyn, New York',
    blurb: 'Started as high-school garage rockers and mutated into one of the strangest guitar acts working, largely on the strength of Cameron Winter’s voice — a croon that snaps into strangled howling with no warning. 2025’s Getting Killed, cut with Kenny Beats from long jam sessions, leans on repetition, abrasive texture and songs that refuse to resolve. Rewarding if you like being slightly off-balance; skip if you want singalongs.',
    soundsLike: ['black midi', 'Talking Heads', 'King Krule'],
    keyTracks: ['Cowboy Nudes', 'Taxes', 'Getting Killed'],
  },
  'Young Miko': {
    genre: 'Latin trap / reggaeton',
    origin: 'Añasco, Puerto Rico',
    blurb: 'Went from tattoo artist and SoundCloud uploads to the Billboard Hot 100 in about two years, and is one of the few openly queer women near the top of urbano. Her flow is loose and unbothered over hard trap beats, with the melodic reggaeton turns that made “Classy 101” inescapable. Her 2024 debut att. proved she’s more than that one song, and the live show is a party.',
    soundsLike: ['Bad Bunny', 'Karol G', 'Villano Antillano'],
    keyTracks: ['Classy 101', 'Riri', 'Lisa'],
  },
  'Kali Uchis': {
    genre: 'R&B / Latin soul',
    origin: 'Alexandria, Virginia',
    blurb: 'The Sunday headliner. Her whole thing is warmth and texture — doo-wop and psychedelic soul melting into bilingual bolero and perreo, delivered in a voice that stays soft even when the lyrics are cutting. Genuine catalog depth: “telepatía” and “Moonlight” are both billion-stream songs, and 2025’s Sincerely hit No. 2. Expect a lush, visually staged closing set rather than a rowdy one.',
    soundsLike: ['Amy Winehouse', 'SZA', 'Erykah Badu'],
    keyTracks: ['telepatía', 'Moonlight', 'After the Storm'],
  },
  'Koo Koo': {
    genre: 'Kids’ dance-pop',
    origin: 'Minneapolis, Minnesota',
    blurb: 'Bryan Atchison and Neil Olstad — formerly Koo Koo Kanga Roo — describe themselves as the Beastie Boys meet Sesame Street. Every song is a sing-along with its own mandatory dance move, and their GoNoodle partnership means a lot of kids in the crowd already know the choreography. A full interactive dance party aimed at families; adults without kids may find it a lot.',
    soundsLike: ['They Might Be Giants', 'Beastie Boys', 'Yo Gabba Gabba'],
    keyTracks: ['Pop See Ko', 'Dinosaur Stomp', 'All I Eat Is Pizza'],
  },
  'Jeffery Lewis': {
    genre: 'Anti-folk / lo-fi',
    origin: 'Lower East Side, New York',
    blurb: 'Lower East Side lifer, comic book artist, and a founding figure of NYC’s anti-folk scene. He talk-sings dense, funny, literate songs about city life, anxiety and underground history — including narrated song-comics where he flips illustrated panels onstage while playing. Not a polished set, and that’s the point; go if you want to actually listen to words. (Usually spelled Jeffrey Lewis everywhere but the festival site.)',
    soundsLike: ['Daniel Johnston', 'The Moldy Peaches', 'Lou Reed'],
    keyTracks: ['Williamsburg Will Oldham Horror', 'The Chelsea Hotel Oral Sex Song', 'History of Punk on the Lower East Side'],
  },
  'Die Spitz': {
    genre: 'Punk / grunge',
    origin: 'Austin, Texas',
    blurb: 'Four women, all around 22, who formed in 2022 and swap instruments mid-set — all four sing and multiple members rotate through drums and guitar. Their Third Man debut Something to Consume swings between snotty pop-punk and outright metal riffing. They’ve opened for Amyl and the Sniffers, Sleater-Kinney and Foo Fighters, and the live show is famously chaotic.',
    soundsLike: ['Amyl and the Sniffers', 'L7', 'Bikini Kill'],
    keyTracks: ['Throw Yourself to the Sword', 'Pop Punk Anthem', 'Punishers'],
  },
  'Gouge Away': {
    genre: 'Hardcore punk / noise rock',
    origin: 'Fort Lauderdale, Florida',
    blurb: 'Hardcore band named after a Pixies song, fronted by Christina Michelle, who alternates between a raw scream and something closer to singing. Their sound pulls from ’90s noise rock — Jesus Lizard, Babes in Toyland — with 2024’s Deep Sage adding real melody and vulnerability after a long burnout-driven hiatus. The heaviest thing on the Sunday bill by a wide margin.',
    soundsLike: ['The Jesus Lizard', 'Babes in Toyland', 'Pixies'],
    keyTracks: ['Idealized', 'Stuck in a Dream', 'Deep Sage'],
  },

});
